services:
  mysql:
    image: mysql:8.0
    container_name: leovegas-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: leovegas
      MYSQL_USER: leovegas
      MYSQL_PASSWORD: leovegas
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
